### ISSUE TITLE
Ghost missing

### ISSUE THREAD

**Issue by ElectronDance** [hundredrabbits/Hiversaires#5]
The blue ghost does not seem to appear even though dots appear when a sighting should occur. (On the first "sighting" in the maze area, three dots appeared.)

**Comment by Rezmason** [comment]
This is a design decision. 👻

As per [https://github.com/hundredrabbits/Hiversaires/commit/738e10b0d2d3501d0e1ed4bfe81eab303bab869c](this commit), the ghost is deactivated across the game— though you can reactivate it in a fork if you like.
